/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Datos.Clsconexion;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Freddy Calahorrano
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    
    Clsconexion _agenda, _contacto;
    ResultSet rscontactos;
    int clv;
    public Agenda() {
        initComponents();
        archbd.setVisible(false);
        PnlVerAgenda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archbd = new javax.swing.JFileChooser();
        PnlVerAgenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVerAgenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnuAbirBase = new javax.swing.JMenuItem();
        MnuSalir = new javax.swing.JMenuItem();
        MnuAgenda = new javax.swing.JMenu();
        MnuVerAenda = new javax.swing.JMenuItem();
        MnNueContacto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archbdActionPerformed(evt);
            }
        });
        getContentPane().add(archbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA");

        BtnVerAgenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnVerAgenda.setText("Ver Agenda");
        BtnVerAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAgendaActionPerformed(evt);
            }
        });

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Apellido", "Direccion", "Telèfono", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        javax.swing.GroupLayout PnlVerAgendaLayout = new javax.swing.GroupLayout(PnlVerAgenda);
        PnlVerAgenda.setLayout(PnlVerAgendaLayout);
        PnlVerAgendaLayout.setHorizontalGroup(
            PnlVerAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerAgendaLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(PnlVerAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlVerAgendaLayout.createSequentialGroup()
                        .addGroup(PnlVerAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnVerAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlVerAgendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        PnlVerAgendaLayout.setVerticalGroup(
            PnlVerAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVerAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnlVerAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        jMenu1.setText("Base de Datos");

        MnuAbirBase.setText("Abrir");
        MnuAbirBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAbirBaseActionPerformed(evt);
            }
        });
        jMenu1.add(MnuAbirBase);

        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MnuSalir);

        jMenuBar1.add(jMenu1);

        MnuAgenda.setText("Agenda");

        MnuVerAenda.setText("Ver Agenda");
        MnuVerAenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuVerAendaActionPerformed(evt);
            }
        });
        MnuAgenda.add(MnuVerAenda);

        MnNueContacto.setText("Nuevo Contacto");
        MnuAgenda.add(MnNueContacto);

        jMenuBar1.add(MnuAgenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAbirBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAbirBaseActionPerformed
        archbd.setVisible(true);
        PnlVerAgenda.setVisible(false);
        
    }//GEN-LAST:event_MnuAbirBaseActionPerformed

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void MnuVerAendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuVerAendaActionPerformed
        archbd.setVisible(false);
    }//GEN-LAST:event_MnuVerAendaActionPerformed

    private void BtnVerAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerAgendaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblAgenda.getModel();

        String[] c = new String[11];

        try {
            for (int i = 0; i < 12; i++) {
                _agenda.siguiente();
                c[0] = String.valueOf(_agenda._cliente().getInt("claveContacto"));
                c[1] = _agenda._cliente().getString("nomContacto");
                c[2] = _agenda._cliente().getString("apellContacto");
                c[3] = _agenda._cliente().getString("dirContacto");
                c[4] = _agenda._cliente().getString("tlfContacto");
                c[5] = _agenda._cliente().getString("celContacto");

                modelo.addRow(c);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblAgenda.setModel(modelo);
    }//GEN-LAST:event_BtnVerAgendaActionPerformed

    private void archbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archbdActionPerformed
        File f = archbd.getSelectedFile();
        String base = f.getAbsolutePath();
        _agenda = new Clsconexion(base);
        try {
            _agenda.consulta("TbAgenda");
        } catch (SQLException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_archbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVerAgenda;
    private javax.swing.JMenuItem MnNueContacto;
    private javax.swing.JMenuItem MnuAbirBase;
    private javax.swing.JMenu MnuAgenda;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JMenuItem MnuVerAenda;
    private javax.swing.JPanel PnlVerAgenda;
    private javax.swing.JFileChooser archbd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}
